//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

pub use super::loss_contracts::Entity as LossContracts;
pub use super::loss_logs::Entity as LossLogs;
pub use super::payment_logs::Entity as PaymentLogs;
pub use super::users::Entity as Users;
