//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "approval_status")]
pub enum ApprovalStatus {
    #[sea_orm(string_value = "approved")]
    Approved,
    #[sea_orm(string_value = "bypassed")]
    Bypassed,
    #[sea_orm(string_value = "denied")]
    Denied,
    #[sea_orm(string_value = "pending")]
    Pending,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "loss_contract_type")]
pub enum LossContractType {
    #[sea_orm(string_value = "escape")]
    Escape,
    #[sea_orm(string_value = "loss")]
    Loss,
}
