//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub torn_api_key: String,
    pub allow_defend_contract_requests: Option<bool>,
    pub allow_auto_defend_contract_link: Option<bool>,
    pub allow_auto_defend_contract_log: Option<bool>,
    pub auto_defend_contract_duration: Option<i32>,
    pub auto_defend_contract_hit_limit: Option<i32>,
    pub auto_defend_contract_price: Decimal,
    pub allow_loss_contract_requests: Option<bool>,
    pub allow_auto_loss_contract_link: Option<bool>,
    pub allow_auto_loss_contract_log: Option<bool>,
    pub auto_loss_contract_duration: Option<i32>,
    pub auto_loss_contract_hit_limit: Option<i32>,
    pub auto_loss_contract_price: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
