[package]
name = "tornhq"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["api", "database"]

[dependencies]
api = { version = "0.1.0", path = "api" }
database = { version = "0.1.0", path = "database" }
